#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VedicsSangrah.Resource", IsApplication=true)]

namespace VedicsSangrah
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040068
			public const int AartiSangrahButton = 2130968680;
			
			// aapt resource value: 0x7f04001c
			public const int AashtalaxmistotrawebView1 = 2130968604;
			
			// aapt resource value: 0x7f040094
			public const int Achyutashtakam = 2130968724;
			
			// aapt resource value: 0x7f040018
			public const int AchyutashtakamStotramwebView1 = 2130968600;
			
			// aapt resource value: 0x7f040095
			public const int AdityaHridayaStotram = 2130968725;
			
			// aapt resource value: 0x7f040019
			public const int AdityahRidayastotrawebView1 = 2130968601;
			
			// aapt resource value: 0x7f040000
			public const int AnnapurnaAartiButton = 2130968576;
			
			// aapt resource value: 0x7f04001a
			public const int AnnapurnaAartiwebView1 = 2130968602;
			
			// aapt resource value: 0x7f040024
			public const int AnnapurnaChalisaButton = 2130968612;
			
			// aapt resource value: 0x7f04001b
			public const int AnnapurnaChalisawebView1 = 2130968603;
			
			// aapt resource value: 0x7f040096
			public const int AshtaLakshmiStotram = 2130968726;
			
			// aapt resource value: 0x7f040026
			public const int BhairavChalisaButton = 2130968614;
			
			// aapt resource value: 0x7f04001d
			public const int BhairavChalisawebView1 = 2130968605;
			
			// aapt resource value: 0x7f040025
			public const int BramhaChalisaButton = 2130968613;
			
			// aapt resource value: 0x7f04001e
			public const int BramhaChalisawebView1 = 2130968606;
			
			// aapt resource value: 0x7f040052
			public const int BudhvarVratKathaButton = 2130968658;
			
			// aapt resource value: 0x7f04001f
			public const int BudhwarVratKathawebView1 = 2130968607;
			
			// aapt resource value: 0x7f040067
			public const int ChalisaSangrahButton = 2130968679;
			
			// aapt resource value: 0x7f040001
			public const int ChamundaDeviAartiButton = 2130968577;
			
			// aapt resource value: 0x7f04003d
			public const int ChamundaDeviAartiwebView1 = 2130968637;
			
			// aapt resource value: 0x7f04005a
			public const int ChhathKathaButton = 2130968666;
			
			// aapt resource value: 0x7f04003e
			public const int ChhathVratKathawebView1 = 2130968638;
			
			// aapt resource value: 0x7f040027
			public const int ChitraguptaChalisaButton = 2130968615;
			
			// aapt resource value: 0x7f04003f
			public const int ChitraguptaChalisawebView1 = 2130968639;
			
			// aapt resource value: 0x7f04005b
			public const int ChitraguptaKathaButton = 2130968667;
			
			// aapt resource value: 0x7f040040
			public const int ChitraguptaPujaKathawebView1 = 2130968640;
			
			// aapt resource value: 0x7f040028
			public const int DurgaChalisaButton = 2130968616;
			
			// aapt resource value: 0x7f040041
			public const int DurgaChalisawebView1 = 2130968641;
			
			// aapt resource value: 0x7f0400a7
			public const int DurgaSaptsloki = 2130968743;
			
			// aapt resource value: 0x7f040097
			public const int DwadashJyotirLingam = 2130968727;
			
			// aapt resource value: 0x7f040098
			public const int EkShlokiSundarkand = 2130968728;
			
			// aapt resource value: 0x7f040002
			public const int GaneshAartiButton = 2130968578;
			
			// aapt resource value: 0x7f040044
			public const int GaneshAartiwebView1 = 2130968644;
			
			// aapt resource value: 0x7f040020
			public const int GaneshChalisaButton = 2130968608;
			
			// aapt resource value: 0x7f040045
			public const int GaneshChalisaWebView1 = 2130968645;
			
			// aapt resource value: 0x7f0400a8
			public const int GauriAshtotraNamavali = 2130968744;
			
			// aapt resource value: 0x7f040003
			public const int GayatriAartiButton = 2130968579;
			
			// aapt resource value: 0x7f040029
			public const int GayatriChalisaButton = 2130968617;
			
			// aapt resource value: 0x7f040046
			public const int GayatriChalisawebView1 = 2130968646;
			
			// aapt resource value: 0x7f0400a9
			public const int GayatriKavacham = 2130968745;
			
			// aapt resource value: 0x7f040047
			public const int GayatriMataAartiwebView1 = 2130968647;
			
			// aapt resource value: 0x7f0400ad
			public const int GovindDamodarStotram = 2130968749;
			
			// aapt resource value: 0x7f040004
			public const int HanumanAartiaButton = 2130968580;
			
			// aapt resource value: 0x7f040021
			public const int HanumanChalisaButton = 2130968609;
			
			// aapt resource value: 0x7f040049
			public const int HanumanChalisawWebView1 = 2130968649;
			
			// aapt resource value: 0x7f040048
			public const int HanumanJeeAartiwebView1 = 2130968648;
			
			// aapt resource value: 0x7f0400aa
			public const int HariNaamMalaStotram = 2130968746;
			
			// aapt resource value: 0x7f040099
			public const int HariStotram = 2130968729;
			
			// aapt resource value: 0x7f04004a
			public const int HariStotramwebView1 = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int HimalayakritShivStotramwebView1 = 2130968651;
			
			// aapt resource value: 0x7f04009a
			public const int HimalaykritShivStotram = 2130968730;
			
			// aapt resource value: 0x7f040058
			public const int JanmastamiKathaButton = 2130968664;
			
			// aapt resource value: 0x7f04004c
			public const int JanmastamiVratKathawebView1 = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int KaaliMaaAartiwebView1 = 2130968653;
			
			// aapt resource value: 0x7f040005
			public const int KaliMaaAartiButton = 2130968581;
			
			// aapt resource value: 0x7f04002a
			public const int KaliMaaChalisaButton = 2130968618;
			
			// aapt resource value: 0x7f04004e
			public const int KaliMaaChalisawebView1 = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int KarwaChauthKathawebView1 = 2130968655;
			
			// aapt resource value: 0x7f04006a
			public const int KathaKandSangrahButton = 2130968682;
			
			// aapt resource value: 0x7f04002b
			public const int KhatuShyamChalisaButton = 2130968619;
			
			// aapt resource value: 0x7f04005c
			public const int KhatuShyamChalisawebView1 = 2130968668;
			
			// aapt resource value: 0x7f040006
			public const int KrishnaAartiButton = 2130968582;
			
			// aapt resource value: 0x7f04005d
			public const int KrishnaAartiwebView1 = 2130968669;
			
			// aapt resource value: 0x7f0400ab
			public const int KrishnaAshtakam = 2130968747;
			
			// aapt resource value: 0x7f040023
			public const int KrishnaChalisaButton = 2130968611;
			
			// aapt resource value: 0x7f04005e
			public const int KrishnaChalisaWebView1 = 2130968670;
			
			// aapt resource value: 0x7f04002c
			public const int KuberChalisaButton = 2130968620;
			
			// aapt resource value: 0x7f04005f
			public const int KuberChalisawebView1 = 2130968671;
			
			// aapt resource value: 0x7f040007
			public const int KunjBihariJeeAartiButton = 2130968583;
			
			// aapt resource value: 0x7f040060
			public const int KunjBihariJeeAartiwebView1 = 2130968672;
			
			// aapt resource value: 0x7f04002d
			public const int LakshmiChalisaButton = 2130968621;
			
			// aapt resource value: 0x7f040061
			public const int LakshmiChalisawebView1 = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int LakshmiMaaAartiwebView1 = 2130968674;
			
			// aapt resource value: 0x7f040008
			public const int LaxhmiMaaAartiButton = 2130968584;
			
			// aapt resource value: 0x7f04009b
			public const int Lingastakam = 2130968731;
			
			// aapt resource value: 0x7f040063
			public const int LingastakamwebView1 = 2130968675;
			
			// aapt resource value: 0x7f04009c
			public const int Madhurastakam = 2130968732;
			
			// aapt resource value: 0x7f040064
			public const int MadhurastakamwebView1 = 2130968676;
			
			// aapt resource value: 0x7f04002e
			public const int MahaKaliMaaChalisaButton = 2130968622;
			
			// aapt resource value: 0x7f040065
			public const int MahaKaliMaaChalisawebView1 = 2130968677;
			
			// aapt resource value: 0x7f0400ac
			public const int MahaMritunjayStotram = 2130968748;
			
			// aapt resource value: 0x7f040059
			public const int MahaShivratriKathaButton = 2130968665;
			
			// aapt resource value: 0x7f040066
			public const int MahaShivratriKathawebView1 = 2130968678;
			
			// aapt resource value: 0x7f040051
			public const int MangalvarKathaButton = 2130968657;
			
			// aapt resource value: 0x7f04006b
			public const int MangalwarVratKathawebView1 = 2130968683;
			
			// aapt resource value: 0x7f04000c
			public const int MataRaniSatiAartiButton = 2130968588;
			
			// aapt resource value: 0x7f04002f
			public const int NavgrahChalisaButton = 2130968623;
			
			// aapt resource value: 0x7f04006c
			public const int NavgrahChalisawebView1 = 2130968684;
			
			// aapt resource value: 0x7f040030
			public const int ParvatiChalisaButton = 2130968624;
			
			// aapt resource value: 0x7f04006d
			public const int ParvatiChalisawebView1 = 2130968685;
			
			// aapt resource value: 0x7f040009
			public const int ParvatiMaaAartiButton = 2130968585;
			
			// aapt resource value: 0x7f04006e
			public const int ParvatiMaaAartiwebView1 = 2130968686;
			
			// aapt resource value: 0x7f0400ae
			public const int RadhaAshtakam = 2130968750;
			
			// aapt resource value: 0x7f040031
			public const int RadhaChalisaButton = 2130968625;
			
			// aapt resource value: 0x7f04006f
			public const int RadhaChalisawebView1 = 2130968687;
			
			// aapt resource value: 0x7f04000a
			public const int RadhaJeeAartiButton = 2130968586;
			
			// aapt resource value: 0x7f040070
			public const int RadhaJeeAartiwebView1 = 2130968688;
			
			// aapt resource value: 0x7f040032
			public const int RamChalisaButton = 2130968626;
			
			// aapt resource value: 0x7f040071
			public const int RamChalisawebView1 = 2130968689;
			
			// aapt resource value: 0x7f04009d
			public const int RamRakshaStotram = 2130968733;
			
			// aapt resource value: 0x7f040073
			public const int RamRakshaStotramwebView1 = 2130968691;
			
			// aapt resource value: 0x7f04009e
			public const int RamStuti = 2130968734;
			
			// aapt resource value: 0x7f040074
			public const int RamStutiwebView1 = 2130968692;
			
			// aapt resource value: 0x7f040072
			public const int RamchandraAartiwebView1 = 2130968690;
			
			// aapt resource value: 0x7f04000b
			public const int RamchandraJeeAartiButton = 2130968587;
			
			// aapt resource value: 0x7f040075
			public const int RaniSatiDeviJeewebView1 = 2130968693;
			
			// aapt resource value: 0x7f040056
			public const int RavivarVratKathaButton = 2130968662;
			
			// aapt resource value: 0x7f040076
			public const int RavivarVratKathawebView1 = 2130968694;
			
			// aapt resource value: 0x7f04009f
			public const int Rudrastakam = 2130968735;
			
			// aapt resource value: 0x7f040077
			public const int RudrastakamwebView1 = 2130968695;
			
			// aapt resource value: 0x7f04000d
			public const int SaiBabaAartiButton = 2130968589;
			
			// aapt resource value: 0x7f040033
			public const int SaiChalisaButton = 2130968627;
			
			// aapt resource value: 0x7f040079
			public const int SaiChalisawebView1 = 2130968697;
			
			// aapt resource value: 0x7f040078
			public const int SaibabaAartiwebView1 = 2130968696;
			
			// aapt resource value: 0x7f0400a0
			public const int SankatNashakGaneshStotram = 2130968736;
			
			// aapt resource value: 0x7f04007a
			public const int SankatNashakGaneshStotramwebView1 = 2130968698;
			
			// aapt resource value: 0x7f04000e
			public const int SantoshiMaaAartiButton = 2130968590;
			
			// aapt resource value: 0x7f040034
			public const int SantoshiMaaChalisaButton = 2130968628;
			
			// aapt resource value: 0x7f04007b
			public const int SantoshiMaaChalisawebView1 = 2130968699;
			
			// aapt resource value: 0x7f04007c
			public const int SantoshiMataAartiwebView1 = 2130968700;
			
			// aapt resource value: 0x7f040036
			public const int SaraswatiChalisaButton = 2130968630;
			
			// aapt resource value: 0x7f04007e
			public const int SaraswatiChalisawebView1 = 2130968702;
			
			// aapt resource value: 0x7f04000f
			public const int SaraswatiPrarthnaButton = 2130968591;
			
			// aapt resource value: 0x7f04007f
			public const int SaraswatiPrarthnawebView1 = 2130968703;
			
			// aapt resource value: 0x7f0400a1
			public const int SaraswatiStotram = 2130968737;
			
			// aapt resource value: 0x7f04007d
			public const int SaraswatiStotramwebView1 = 2130968701;
			
			// aapt resource value: 0x7f040010
			public const int SatyaNarayanJeeAartiButton = 2130968592;
			
			// aapt resource value: 0x7f040080
			public const int SatyaNarayanJeeAartiwebView1 = 2130968704;
			
			// aapt resource value: 0x7f040081
			public const int SeetaJeeAartiwebView1 = 2130968705;
			
			// aapt resource value: 0x7f040011
			public const int SeetaMataAartiButton = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int ShaniDevAartiButton = 2130968594;
			
			// aapt resource value: 0x7f040082
			public const int ShaniDevJeeAartiwebView1 = 2130968706;
			
			// aapt resource value: 0x7f040055
			public const int ShanivarVratKathaButton = 2130968661;
			
			// aapt resource value: 0x7f040083
			public const int ShanivarVratKathawebView1 = 2130968707;
			
			// aapt resource value: 0x7f040037
			public const int SheetlaChalisaButton = 2130968631;
			
			// aapt resource value: 0x7f040084
			public const int SheetlaChalisawebView1 = 2130968708;
			
			// aapt resource value: 0x7f040085
			public const int ShivApradhaKshamaPrarthnaStotramwebView1 = 2130968709;
			
			// aapt resource value: 0x7f040022
			public const int ShivChalisaButton = 2130968610;
			
			// aapt resource value: 0x7f040013
			public const int ShivJeeAartiButton = 2130968595;
			
			// aapt resource value: 0x7f040086
			public const int ShivJeeAartiwebView1 = 2130968710;
			
			// aapt resource value: 0x7f040088
			public const int ShivPanchAksharStotramwebView1 = 2130968712;
			
			// aapt resource value: 0x7f040089
			public const int ShivShaktiKritamGaneshStotramwebView1 = 2130968713;
			
			// aapt resource value: 0x7f04008a
			public const int ShivTandavStotramwebView1 = 2130968714;
			
			// aapt resource value: 0x7f0400a3
			public const int ShivaApradhKshamapanStotram = 2130968739;
			
			// aapt resource value: 0x7f0400a6
			public const int ShivaAshtakam = 2130968742;
			
			// aapt resource value: 0x7f040087
			public const int ShivaChalisaWebView1 = 2130968711;
			
			// aapt resource value: 0x7f0400a2
			public const int ShivaPanchaksharaStotram = 2130968738;
			
			// aapt resource value: 0x7f0400a4
			public const int ShivaShaktiKritamGaneshStotram = 2130968740;
			
			// aapt resource value: 0x7f0400a5
			public const int ShivaTandavStotram = 2130968741;
			
			// aapt resource value: 0x7f04008b
			public const int ShreeSaptslokiDurgawebView1 = 2130968715;
			
			// aapt resource value: 0x7f040035
			public const int ShreeShaniDevChalisaButton = 2130968629;
			
			// aapt resource value: 0x7f04008c
			public const int ShreeShaniDevChalisawebView1 = 2130968716;
			
			// aapt resource value: 0x7f04008d
			public const int ShreeShivashtakamwebView1 = 2130968717;
			
			// aapt resource value: 0x7f04008e
			public const int ShriGauriAshtottaraNamavaliwebView1 = 2130968718;
			
			// aapt resource value: 0x7f04008f
			public const int ShriGayatriKavachamwebView1 = 2130968719;
			
			// aapt resource value: 0x7f040090
			public const int ShriHariNaamMalaStrotramwebView1 = 2130968720;
			
			// aapt resource value: 0x7f040054
			public const int ShukraVarVratKathaButton = 2130968660;
			
			// aapt resource value: 0x7f040091
			public const int ShukravarVratKathawebView1 = 2130968721;
			
			// aapt resource value: 0x7f040014
			public const int ShyamBabaAartiButton = 2130968596;
			
			// aapt resource value: 0x7f040092
			public const int ShyamBabaAartiwebView1 = 2130968722;
			
			// aapt resource value: 0x7f040050
			public const int SomvarVratKathaButton = 2130968656;
			
			// aapt resource value: 0x7f040093
			public const int SomvarVratKathawebView1 = 2130968723;
			
			// aapt resource value: 0x7f040069
			public const int StotraSangrahButton = 2130968681;
			
			// aapt resource value: 0x7f0400b3
			public const int SundarKaandwebView1 = 2130968755;
			
			// aapt resource value: 0x7f040057
			public const int SundarKandButton = 2130968663;
			
			// aapt resource value: 0x7f0400af
			public const int SuryaAshtakam = 2130968751;
			
			// aapt resource value: 0x7f040038
			public const int SuryaChalisaButton = 2130968632;
			
			// aapt resource value: 0x7f0400b4
			public const int SuryaChalisawebView1 = 2130968756;
			
			// aapt resource value: 0x7f040015
			public const int SuryaDevAartiButton = 2130968597;
			
			// aapt resource value: 0x7f0400b5
			public const int SuryaDevAartiwebView1 = 2130968757;
			
			// aapt resource value: 0x7f040039
			public const int TulsiChalisaButton = 2130968633;
			
			// aapt resource value: 0x7f0400b6
			public const int TulsiChalisawebView1 = 2130968758;
			
			// aapt resource value: 0x7f04003a
			public const int VashnoDeviChalisaButton = 2130968634;
			
			// aapt resource value: 0x7f0400b7
			public const int VashnoDeviChalisawebView1 = 2130968759;
			
			// aapt resource value: 0x7f04003b
			public const int VindhyeshwariChalisaButton = 2130968635;
			
			// aapt resource value: 0x7f0400b8
			public const int VindhyeshwariChalisawebView1 = 2130968760;
			
			// aapt resource value: 0x7f0400b0
			public const int VindhyeshwariStotram = 2130968752;
			
			// aapt resource value: 0x7f0400b2
			public const int VishnoShatnaamStotram = 2130968754;
			
			// aapt resource value: 0x7f0400b1
			public const int VishnorAshtaVinshatiNaamStotram = 2130968753;
			
			// aapt resource value: 0x7f04003c
			public const int VishnuChalisaButton = 2130968636;
			
			// aapt resource value: 0x7f0400b9
			public const int VishnuChalisawebView1 = 2130968761;
			
			// aapt resource value: 0x7f040016
			public const int VishnuJeeAartiButton = 2130968598;
			
			// aapt resource value: 0x7f0400ba
			public const int VishnuJeeAartiwebView1 = 2130968762;
			
			// aapt resource value: 0x7f040017
			public const int VrihaspatiDevAartiButton = 2130968599;
			
			// aapt resource value: 0x7f0400bb
			public const int VrihaspatiDevAartiwebView1 = 2130968763;
			
			// aapt resource value: 0x7f040053
			public const int VrihaspatiVarKathaButton = 2130968659;
			
			// aapt resource value: 0x7f0400bc
			public const int VrihaspativarVratKathawebView1 = 2130968764;
			
			// aapt resource value: 0x7f040042
			public const int dwadasa_jyotirlingamwebView1 = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int eksloki_sundarkandwebView1 = 2130968643;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AartiMainPage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AchyutashtakamStotram = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AdityahRidayastotra = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AnnapurnaAarti = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int AnnapurnaChalisaa = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Ashtalaxmistotra = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int BhairavChalisa = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int BramhaChalisa = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int BudhwarVratKatha = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ChalisaMainPage = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ChamundaDeviAarti = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ChhathVratKatha = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ChitraguptaChalisa = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ChitraguptaPujaKatha = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int DurgaChalisa = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dwadasa_jyotirlingam = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Eksloki_sundarkand = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int GaneshAarti = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int GaneshJeeChalisa = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int GayatriChalisa = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int GayatriMataAarti = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int HanumanJeeAarti = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int HanumanJeeChalisa = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int HariStotram = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int HimalayakritShivStotram = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int JanmastamiVratKatha = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int KaaliMaaAarti = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int KaaliMaaChalisa = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int KarwaChauthKatha = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int KathaKaand = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int KhatuShyamChalisa = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int KrishnaAarti = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int KrishnaJeeChalisa = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int KuberChalisa = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int KunjBihariJeeAarti = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int LakshmiChalisa = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int LaxhmiMaaAarti = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Lingastakam = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Madhurastakam = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int MahaKaaliMaaChalisa = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int MahaSivratriKatha = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Main = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int MangalwarVratKatha = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int NavgrahChalisa = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ParvatiChalisa = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ParvatiMaaAarti = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int RadhaChalisa = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int RadhaJeeAarti = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int RamChalisa = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int RamChandraAarti = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int RamRakshaStotram = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int RamStuti = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int RaniSatiJeeAarti = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int RavivarVratKatha = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Rudrastakam = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int SaibabaAarti = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int SaiChalisa = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int SankatNashakGaneshStotram = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int SantoshiMaaChalisa = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int SantoshiMataAarti = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int SarasVatsalStotram = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int SaraswatiChalisa = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int SaraswatiPrarthna = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int SatyanarayanJeeAarti = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int SeetaJeeAarti = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ShaniDevJeeAarti = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ShanikvarVratKatha = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int SheetlaChalisa = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ShivApradhaKshamaPrarthnaStotram = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ShivJeeAarti = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ShivJeeChalisa = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ShivPanchAksharStotram = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ShivShaktiKritamGaneshStotram = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ShivTandavStotram = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ShreeSaptslokiDurga = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ShreeShaniDevChalisa = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ShreeShivashtakam = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ShriGauriAshtottaraNamavali = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ShriGayatriKavacham = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ShriHariNaamMalaStrotram = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ShukravarVratKatha = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ShyamBabaAarti = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int SomvarVratKatha = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int StotraSangrah = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int Sundarkaand = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int SuryaChalisa = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int SuryaDevAarti = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int TulsiChalisa = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int VasnhoDeviChalisa = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int VindhyeshwariChalisa = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int VishnuChalisa = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int VishnuJeeAarti = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int VrihaspatiDevAarti = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int VrihaspativarVratKatha = 2130837597;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
