#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VedicsSangrah.Resource", IsApplication=true)]

namespace VedicsSangrah
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040044
			public const int AartiSangrahButton = 2130968644;
			
			// aapt resource value: 0x7f040000
			public const int AnnapurnaAartiButton = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int AnnapurnaAartiwebView1 = 2130968600;
			
			// aapt resource value: 0x7f040020
			public const int AnnapurnaChalisaButton = 2130968608;
			
			// aapt resource value: 0x7f040019
			public const int AnnapurnaChalisawebView1 = 2130968601;
			
			// aapt resource value: 0x7f040022
			public const int BhairavChalisaButton = 2130968610;
			
			// aapt resource value: 0x7f04001a
			public const int BhairavChalisawebView1 = 2130968602;
			
			// aapt resource value: 0x7f040021
			public const int BramhaChalisaButton = 2130968609;
			
			// aapt resource value: 0x7f04001b
			public const int BramhaChalisawebView1 = 2130968603;
			
			// aapt resource value: 0x7f040043
			public const int ChalisaSangrahButton = 2130968643;
			
			// aapt resource value: 0x7f040001
			public const int ChamundaDeviAartiButton = 2130968577;
			
			// aapt resource value: 0x7f040023
			public const int ChitraguptaChalisaButton = 2130968611;
			
			// aapt resource value: 0x7f040038
			public const int ChitraguptaChalisawebView1 = 2130968632;
			
			// aapt resource value: 0x7f040024
			public const int DurgaChalisaButton = 2130968612;
			
			// aapt resource value: 0x7f040039
			public const int DurgaChalisawebView1 = 2130968633;
			
			// aapt resource value: 0x7f040002
			public const int GaneshAartiButton = 2130968578;
			
			// aapt resource value: 0x7f04001c
			public const int GaneshChalisaButton = 2130968604;
			
			// aapt resource value: 0x7f04003a
			public const int GaneshChalisaWebView1 = 2130968634;
			
			// aapt resource value: 0x7f040003
			public const int GayatriAartiButton = 2130968579;
			
			// aapt resource value: 0x7f040025
			public const int GayatriChalisaButton = 2130968613;
			
			// aapt resource value: 0x7f04003b
			public const int GayatriChalisawebView1 = 2130968635;
			
			// aapt resource value: 0x7f040004
			public const int HanumanAartiaButton = 2130968580;
			
			// aapt resource value: 0x7f04001d
			public const int HanumanChalisaButton = 2130968605;
			
			// aapt resource value: 0x7f04003c
			public const int HanumanChalisawWebView1 = 2130968636;
			
			// aapt resource value: 0x7f040005
			public const int KaliMaaAartiButton = 2130968581;
			
			// aapt resource value: 0x7f040026
			public const int KaliMaaChalisaButton = 2130968614;
			
			// aapt resource value: 0x7f04003d
			public const int KaliMaaChalisawebView1 = 2130968637;
			
			// aapt resource value: 0x7f040027
			public const int KhatuShyamChalisaButton = 2130968615;
			
			// aapt resource value: 0x7f04003e
			public const int KhatuShyamChalisawebView1 = 2130968638;
			
			// aapt resource value: 0x7f04001f
			public const int KrishnaChalisaButton = 2130968607;
			
			// aapt resource value: 0x7f04003f
			public const int KrishnaChalisaWebView1 = 2130968639;
			
			// aapt resource value: 0x7f040028
			public const int KuberChalisaButton = 2130968616;
			
			// aapt resource value: 0x7f040040
			public const int KuberChalisawebView1 = 2130968640;
			
			// aapt resource value: 0x7f040006
			public const int KunjBihariJeeAartiButton = 2130968582;
			
			// aapt resource value: 0x7f040029
			public const int LakshmiChalisaButton = 2130968617;
			
			// aapt resource value: 0x7f040041
			public const int LakshmiChalisawebView1 = 2130968641;
			
			// aapt resource value: 0x7f040007
			public const int LaxhmiMaaAarti = 2130968583;
			
			// aapt resource value: 0x7f04002a
			public const int MahaKaliMaaChalisaButton = 2130968618;
			
			// aapt resource value: 0x7f040042
			public const int MahaKaliMaaChalisawebView1 = 2130968642;
			
			// aapt resource value: 0x7f04000b
			public const int MataRaniSatiAartiButton = 2130968587;
			
			// aapt resource value: 0x7f04002b
			public const int NavgrahChalisaButton = 2130968619;
			
			// aapt resource value: 0x7f040045
			public const int NavgrahChalisawebView1 = 2130968645;
			
			// aapt resource value: 0x7f04002c
			public const int ParvatiChalisaButton = 2130968620;
			
			// aapt resource value: 0x7f040046
			public const int ParvatiChalisawebView1 = 2130968646;
			
			// aapt resource value: 0x7f040008
			public const int ParvatiMaaAartiButton = 2130968584;
			
			// aapt resource value: 0x7f04002d
			public const int RadhaChalisaButton = 2130968621;
			
			// aapt resource value: 0x7f040047
			public const int RadhaChalisawebView1 = 2130968647;
			
			// aapt resource value: 0x7f040009
			public const int RadhaJeeAartiButton = 2130968585;
			
			// aapt resource value: 0x7f04002e
			public const int RamChalisaButton = 2130968622;
			
			// aapt resource value: 0x7f040048
			public const int RamChalisawebView1 = 2130968648;
			
			// aapt resource value: 0x7f04000a
			public const int RamchandraJeeAartiButton = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int SaiBabaAartiButton = 2130968588;
			
			// aapt resource value: 0x7f04002f
			public const int SaiChalisaButton = 2130968623;
			
			// aapt resource value: 0x7f040049
			public const int SaiChalisawebView1 = 2130968649;
			
			// aapt resource value: 0x7f04000d
			public const int SantoshiMaaAartiButton = 2130968589;
			
			// aapt resource value: 0x7f040030
			public const int SantoshiMaaChalisaButton = 2130968624;
			
			// aapt resource value: 0x7f04004a
			public const int SantoshiMaaChalisawebView1 = 2130968650;
			
			// aapt resource value: 0x7f040016
			public const int SaraswatiChalisaButton = 2130968598;
			
			// aapt resource value: 0x7f04004b
			public const int SaraswatiChalisawebView1 = 2130968651;
			
			// aapt resource value: 0x7f04000e
			public const int SaraswatiPrarthnaButton = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int SatyaNarayanJeeAartiButton = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int SeetaMataAartiButton = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int ShaniDevAartiButton = 2130968593;
			
			// aapt resource value: 0x7f040032
			public const int SheetlaChalisaButton = 2130968626;
			
			// aapt resource value: 0x7f04004c
			public const int SheetlaChalisawebView1 = 2130968652;
			
			// aapt resource value: 0x7f04001e
			public const int ShivChalisaButton = 2130968606;
			
			// aapt resource value: 0x7f040012
			public const int ShivJeeAartiButton = 2130968594;
			
			// aapt resource value: 0x7f04004d
			public const int ShivaChalisaWebView1 = 2130968653;
			
			// aapt resource value: 0x7f040031
			public const int ShreeShaniDevChalisaButton = 2130968625;
			
			// aapt resource value: 0x7f04004e
			public const int ShreeShaniDevChalisawebView1 = 2130968654;
			
			// aapt resource value: 0x7f040013
			public const int ShyamBabaAartiButton = 2130968595;
			
			// aapt resource value: 0x7f040033
			public const int SuryaChalisaButton = 2130968627;
			
			// aapt resource value: 0x7f04004f
			public const int SuryaChalisawebView1 = 2130968655;
			
			// aapt resource value: 0x7f040014
			public const int SuryaDevAartiButton = 2130968596;
			
			// aapt resource value: 0x7f040034
			public const int TulsiChalisaButton = 2130968628;
			
			// aapt resource value: 0x7f040050
			public const int TulsiChalisawebView1 = 2130968656;
			
			// aapt resource value: 0x7f040035
			public const int VashnoDeviChalisaButton = 2130968629;
			
			// aapt resource value: 0x7f040051
			public const int VashnoDeviChalisawebView1 = 2130968657;
			
			// aapt resource value: 0x7f040036
			public const int VindhyeshwariChalisaButton = 2130968630;
			
			// aapt resource value: 0x7f040052
			public const int VindhyeshwariChalisawebView1 = 2130968658;
			
			// aapt resource value: 0x7f040037
			public const int VishnuChalisaButton = 2130968631;
			
			// aapt resource value: 0x7f040053
			public const int VishnuChalisawebView1 = 2130968659;
			
			// aapt resource value: 0x7f040015
			public const int VishnuJeeAartiButton = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int VrihaspatiDevAartiButton = 2130968599;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AartiMainPage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AnnapurnaAarti = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AnnapurnaChalisaa = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BhairavChalisa = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BramhaChalisa = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ChalisaMainPage = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ChamundaDeviAarti = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ChitraguptaChalisa = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int DurgaChalisa = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int GaneshJeeChalisa = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int GayatriChalisa = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int HanumanJeeChalisa = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int KaaliMaaChalisa = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int KhatuShyamChalisa = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int KrishnaJeeChalisa = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int KuberChalisa = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int LakshmiChalisa = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int MahaKaaliMaaChalisa = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Main = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int NavgrahChalisa = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ParvatiChalisa = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int RadhaChalisa = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int RamChalisa = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int SaiChalisa = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int SantoshiMaaChalisa = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int SaraswatiChalisa = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int SheetlaChalisa = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ShivJeeChalisa = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ShreeShaniDevChalisa = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int SuryaChalisa = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int TulsiChalisa = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int VasnhoDeviChalisa = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int VindhyeshwariChalisa = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int VishnuChalisa = 2130837537;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
